version: "3.1"
services:
  index-daemon:
    # image: misnaged/index-daemon:latest
    build: .
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8000:8000
