{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}}
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    creationPolicy: Owner
  dataFrom: # fetch all properties from a specific Provider data
    - key: {{ .Values.externalSecret.key }}
      version: "{{ .Values.externalSecret.version }}"
{{- end }}