name: Main Actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cargo clippy
        run: cargo clippy --fix
      - name: Git commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'done: cargo clippy lint'
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test

  build_image:
    runs-on: stage
    needs: Tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t index-daemon:latest .
      - run: echo "🍏 This job's status is ${{ job.status }}."

  deploy_image:
    runs-on: stage
    needs: build_image
    defaults:
      run:
        working-directory: /opt/app
    steps:
      - name: Restart docker-compose
        run: docker-compose down && docker-compose up -d
      - name: Clean unused docker images
        run: docker image prune -f 

