name: Main Actions
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cargo clippy
        run: cargo clippy --fix
      - name: Git commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'done: cargo clippy lint'
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test
